### ISSUE TITLE
Lack of Documentation for Securely Accessing Schema Registry via GET Requests in Redpanda

### ISSUE THREAD

**Issue by chauhan-naveen** [redpanda-data/docs#1]
### Issue description

I've been exploring Redpanda's integration with the Schema Registry and its capabilities for managing schemas. In my efforts to interact with the Schema Registry's API via GET requests, especially when TLS (Transport Layer Security) is enforced, I've encountered a significant gap in the available documentation. 

The existing documentation for Redpanda does not cover the necessary steps, commands, or configurations required to securely make GET requests to the Schema Registry's API when TLS is enabled. This information is crucial for users who need to access schemas over a secure connection.

### Updates to existing documentation

https://docs.redpanda.com/current/manage/schema-registry/

**Comment by Feediver1** [comment]
Thanks for the issue @naavveenn --much appreciated. We will notify you after the PR fix has been merged.

**Comment by Deflaimun** [comment]
This issue was closed as part of #5
