### ISSUE TITLE
Docs: Feedback for Install Redpanda for Kubernetes on Cloud

### ISSUE THREAD

**Issue by bdalpe** [redpanda-data/docs#154]
### Issue description

Both of these links 404:

> You can view the resource configuration options, such as storage capacity, network configuration, or TLS configuration in the [cluster_types](https://github.com/redpanda-data/redpanda/blob/dev/src/go/k8s/apis/redpanda/v1alpha1/cluster_types.go) file in GitHub. You can also find additional [sample configuration files](https://github.com/redpanda-data/redpanda/tree/dev/src/go/k8s/config/samples).

### Updates to existing documentation

[Install Redpanda for Kubernetes on Cloud](https://docs.redpanda.com/current/reference/redpanda-operator/kubernetes-qs-cloud/) [Page source](https://github.com/redpanda-data/docs/edit/main/modules/reference/pages/redpanda-operator/kubernetes-qs-cloud.adoc)

**Comment by Deflaimun** [comment]
Hi @bdalpe! Thank you for the issue. The operator for Kubernetes is deprecated. Please check the deprecation notice if you have any questions about it. https://docs.redpanda.com/current/upgrade/deprecated/cluster-resource/

Nevertheless, this is not an excuse for those 404s. We'll look into it and update those links. Thanks for the report!

**Comment by JakeSCahill** [comment]
Hi @bdalpe - as Paulo said, that version of the operator is deprecated. If you want to use the latest operator, you can try these examples: https://docs.redpanda.com/current/deploy/deployment-option/self-hosted/kubernetes/get-started-dev/

As for the 404s, you can find that content here:

- https://github.com/redpanda-data/redpanda/blob/v22.2.x/src/go/k8s/apis/redpanda/v1alpha1/cluster_types.go
- https://github.com/redpanda-data/redpanda/tree/v22.2.x/src/go/k8s/config/samples
