### ISSUE TITLE
Section about enterprise config is missing

### ISSUE THREAD

**Issue by Gerrit-K** [redpanda-data/docs#26]
### Issue description

The [documentation on role bindings](https://github.com/redpanda-data/docs/blob/8577b2f26bee3746d477f59c68b7577cbaffe32a/modules/reference/pages/console/role-bindings.adoc?plain=1#L129) is referencing back to `config.yaml` on how to set the path to `role-bindings.yaml`. However, in the sample `config.yaml` there is no related section anymore.

It was present in [this commit](https://github.com/redpanda-data/docs/blob/fe2e778ba22465952d9e13bedbcf0bd00055a83d/modules/reference/pages/console/config.adoc?plain=1#L337-L344), but apparently got incorrectly replaced during the migration in 20b0dde3ec05d82932fc7bbbca99ada7d3cd7d0a and 6e4413fd64ad2d4b7803fe214d78f92577ae8ba1

### Updates to existing documentation

https://docs.redpanda.com/current/reference/console/config/#sample-configuration

**Comment by JakeSCahill** [comment]
Thanks @Gerrit-K - we are aware of this one and will fix it
