### ISSUE TITLE
Docs: Tiered Storage behaviour on changing

### ISSUE THREAD

**Issue by JFlath** [redpanda-data/docs#30]
### Issue description

It's a small edge case, but it'd be nice if we mentioned somwhere the behaviour when toggling remote writes/reads on a topic, and what that means for the data in cloud storage - e.g. we don't delete that data just because you disable remote writes, and will pick up from where we left off if you re-enable it.

### Updates to existing documentation

[Tiered Storage](https://docs.redpanda.com/current/manage/tiered-storage/) [Page source](https://github.com/redpanda-data/docs/edit/main/modules/manage/pages/tiered-storage.adoc)

**Comment by Feediver1** [comment]
Closing ticket. You can find it/track at: https://github.com/redpanda-data/documentation-private/issues/2015
