### ISSUE TITLE
Docs: Feedback for Deploy a Local Development Cluster with kind or minikube

### ISSUE THREAD

**Issue by JFlath** [redpanda-data/docs#38]
### Issue description

Current versions of the Operator V2 (and hence, Helm chart that uses it) is namespace scoped, meaning that the operator and `Redpanda` object must be created in the same namespace. The examples can be read this way (as we use `<namespace>` everywhere), but it would be good to be explicit about this.

Note that this may change in the future: https://github.com/redpanda-data/redpanda/issues/13308

### Updates to existing documentation

[Deploy a Local Development Cluster with kind or minikube](https://docs.redpanda.com/current/deploy/deployment-option/self-hosted/kubernetes/local-guide/) [Page source](https://github.com/redpanda-data/docs/edit/main/modules/deploy/pages/deployment-option/self-hosted/kubernetes/local-guide.adoc)

**Comment by Feediver1** [comment]
Closing. See https://github.com/redpanda-data/documentation-private/issues/2016
