### ISSUE TITLE
Incorrect advice for detecting production mode

### ISSUE THREAD

**Issue by voutilad** [redpanda-data/docs#573]
### Issue description

The advice in the Production Readiness section about checking for Production Mode is generally wrong. The properties are not cluster properties, so checking via `rpk cluster config` won't help.

### Updates to existing documentation

https://docs.redpanda.com/current/deploy/deployment-option/self-hosted/manual/production/production-readiness/#production-mode

**Comment by Deflaimun** [comment]
Related conversation 
https://redpandadata.slack.com/archives/C01ND4SVB6Z/p1719424041375159
